### ISSUE TITLE
Vergil cannot seize thrones

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#41]
This means PJ3 is unwinnable. PJ2 has an awkward visit event as a workaround right now.

**Comment by Kirbseverywhere** [comment]
Fixed by 5a3a2ec18e304ce716f109d872dbcbc6aeeb9a27

**Comment by Darrman** [comment]
Not actually fixed. Throne still unseizable. 
![FireEmblem3Universes_20](https://user-images.githubusercontent.com/30606600/69750173-0e161d00-1144-11ea-8b4d-3031d58e9af9.png)

**Comment by Darrman** [comment]
Fixed by #45
